FROM eclipse-temurin:21-jdk AS build

WORKDIR /app
COPY . .
RUN chmod +x gradlew && ./gradlew :api-blog:bootJar -x test

FROM eclipse-temurin:21-jre

WORKDIR /app
COPY --from=build /app/api-blog/build/libs/*.jar app.jar

ENTRYPOINT ["java", "-jar", "app.jar"]
